### ISSUE TITLE
Error with SimpleGeoSearcher

### ISSUE THREAD

**Issue by HAKSOAT** [castorini/pyserini#1075]
I was trying to reproduce the [MSMARCO Passage Retrieval experiment](https://github.com/castorini/pyserini/blob/master/docs/experiments-msmarco-passage.md) with the conda setup on Ubuntu using the Windows Subsystem for Linux (WSL). 

On running the command:

```
python -m pyserini.search.lucene \
  --index indexes/lucene-index-msmarco-passage \
  --topics msmarco-passage-dev-subset \
  --output runs/run.msmarco-passage.bm25tuned.txt \
  --output-format msmarco \
  --hits 1000 \
  --bm25 --k1 0.82 --b 0.68
```

I got:

```
Traceback (most recent call last):
  File "/home/haks/anaconda3/envs/pyserini-dev/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/haks/anaconda3/envs/pyserini-dev/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/mnt/c/Users/HAKS/dev/pyserini/pyserini/search/__init__.py", line 17, in <module>
    from .lucene import JQuery, JDisjunctionMaxQueryGenerator, get_topics,\
  File "/mnt/c/Users/HAKS/dev/pyserini/pyserini/search/lucene/__init__.py", line 19, in <module>
    from ._geo_searcher import LuceneGeoSearcher
  File "/mnt/c/Users/HAKS/dev/pyserini/pyserini/search/lucene/_geo_searcher.py", line 39, in <module>
    JGeoSearcher = autoclass('io.anserini.search.SimpleGeoSearcher')
  File "/home/haks/anaconda3/envs/pyserini-dev/lib/python3.8/site-packages/jnius/reflect.py", line 211, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: io/anserini/search/SimpleGeoSearcher java.lang.NoClassDefFoundError
```

Then I tried to re-confirm that everything else was working fine by rebuilding Anserini, copying the fatjar and running unittest test. On running unittest with:

`python -m unittest` 

I got the error:

```
ERROR: tests.test_topics_order (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_topics_order
Traceback (most recent call last):
  File "/home/haks/anaconda3/envs/pyserini-dev/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/haks/anaconda3/envs/pyserini-dev/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/mnt/c/Users/HAKS/dev/pyserini/tests/test_topics_order.py", line 19, in <module>
    from pyserini.query_iterator import DefaultQueryIterator
  File "/mnt/c/Users/HAKS/dev/pyserini/pyserini/query_iterator.py", line 23, in <module>
    from pyserini.search import get_topics, get_topics_with_reader
  File "/mnt/c/Users/HAKS/dev/pyserini/pyserini/search/__init__.py", line 17, in <module>
    from .lucene import JQuery, JDisjunctionMaxQueryGenerator, get_topics,\
  File "/mnt/c/Users/HAKS/dev/pyserini/pyserini/search/lucene/__init__.py", line 19, in <module>
    from ._geo_searcher import LuceneGeoSearcher
  File "/mnt/c/Users/HAKS/dev/pyserini/pyserini/search/lucene/_geo_searcher.py", line 39, in <module>
    JGeoSearcher = autoclass('io.anserini.search.SimpleGeoSearcher')
  File "/home/haks/anaconda3/envs/pyserini-dev/lib/python3.8/site-packages/jnius/reflect.py", line 211, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: io/anserini/search/SimpleGeoSearcher java.lang.NoClassDefFoundError


----------------------------------------------------------------------
Ran 61 tests in 310.031s

FAILED (errors=12)
```

NB: The traceback above contains only the final error from the 12 gotten. The remaining 11 also point to the same issue with `SimpleGeoSearcher`. 

How can I possibly fix this?

**Comment by HAKSOAT** [comment]
Thank you. 

It fixed that issue but another comes up on running the unittest:

```
======================================================================
ERROR: test_msmarco_passage_dev_unicoil_d2q (tests.test_load_topics_qrels.TestLoadTopics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/HAKS/dev/pyserini/tests/test_load_topics_qrels.py", line 360, in test_msmarco_passage_dev_unicoil_d2q
    topics = search.get_topics('msmarco-passage-dev-subset-unicoil-d2q')
  File "/mnt/c/Users/HAKS/dev/pyserini/pyserini/search/lucene/_base.py", line 124, in get_topics
    topics = JTopicReader.getTopicsWithStringIds(JTopics.MSMARCO_PASSAGE_DEV_SUBSET_UNICOIL_D2Q)
AttributeError: type object 'io.anserini.search.topicreader.Topics' has no attribute 'MSMARCO_PASSAGE_DEV_SUBSET_UNICOIL_D2Q'

----------------------------------------------------------------------
Ran 199 tests in 348.772s

FAILED (errors=1)

```


NB: This error does not block me from continuing the experiment's reproduction.

**Comment by lintool** [comment]
Yup, that symbol changed over on the anserini side, and we need to update here also. @MXueguang from our group is on it.

**Comment by HAKSOAT** [comment]
Great. Thank you. Closing this issue now.
