### ISSUE TITLE
run_all_miracl.py bug?

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1325]
Hey @crystina-z @ToluClassics - did we miss something in the refactoring or did I do something wrong?

```
$ python scripts/repro_matrix/run_all_miracl.py 
condition bm25.ar:
  - split: train
    Running: python -m pyserini.search.lucene --language ar --topics tools/topics-and-qrels/topics.miracl-v1.0-ar-train.tsv --index miracl-v1.0-ar --output runs/run.miracl.bm25.ar.train.txt --batch 128 --threads 16 --bm25 --hits 100
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tuna1/scratch/jimmylin/pyserini/pyserini/search/lucene/__main__.py", line 149, in <module>
    query_iterator = get_query_iterator(args.topics, TopicsFormat(args.topics_format))
  File "/tuna1/scratch/jimmylin/pyserini/pyserini/query_iterator.py", line 159, in get_query_iterator
    return mapping[topics_format].from_topics(topics_path)
  File "/tuna1/scratch/jimmylin/pyserini/pyserini/query_iterator.py", line 101, in from_topics
    topics = get_topics(topics_path)
  File "/tuna1/scratch/jimmylin/pyserini/pyserini/search/_base.py", line 436, in get_topics
    raise ValueError(f'Topic {collection_name} Not Found')
ValueError: Topic tools/topics-and-qrels/topics.miracl-v1.0-ar-train.tsv Not Found
```

**Comment by ToluClassics** [comment]
Hi @lintool , We only created regressions for `dev` set

**Comment by lintool** [comment]
Ah, yes, I forgot.

Does it make sense to do better error handling? I.e., if the test queries are not present, just skip those regressions?
