### ISSUE TITLE
editable installation fails with latest setuptools

### ISSUE THREAD

**Issue by nelson-liu** [castorini/pyserini#1545]
When trying to set up an editable installation with `setuptools==67.8.0`, I get the error below. Just thought I'd raise an issue in case you'd like to change how version identifiers are formatted in a future release. Thanks!

```
$ pip install -e .
Obtaining file:///home/nfliu/git/pyserini
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      /home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/dist.py:520: SetuptoolsDeprecationWarning: Invalid version: '0.21.1-2cr-test'.
      !!

              ********************************************************************************
              The version specified is not a valid version according to PEP 440.
              This may not work as expected with newer versions of
              setuptools, pip, and PyPI.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************

      !!
        self._validate_version(self.metadata.version)
      running egg_info
      /home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/command/egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: '0.21.1-2cr-test'.
      !!

              ********************************************************************************
              Version '0.21.1-2cr-test' is not valid according to PEP 440.

              Please make sure to specify a valid version for your package.
              Also note that future releases of setuptools may halt the build process
              if an invalid version is given.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************

      !!
        return _normalization.best_effort_version(tagged)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/nfliu/git/pyserini/setup.py", line 14, in <module>
          setuptools.setup(
        File "/home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
          parsed_version = packaging.version.Version(self.egg_version)
        File "/home/nfliu/miniconda3/envs/pyserini/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '0.21.1-2cr-test'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by lintool** [comment]
Thanks for noting. I forgot to revert some things I was testing on Test PyPI.
Fixed via https://github.com/castorini/pyserini/pull/1546
