### ISSUE TITLE
Required upgrade to faiss(-cpu) 1.7.4

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1564]
Noting for the record -

With https://github.com/castorini/pyserini/pull/1562 - I was getting the following error:

```
$ python -m pyserini.search.faiss \
>   --threads 16 --batch-size 128 \
>   --index msmarco-v1-passage.openai-ada2 \
>   --topics dl19-passage --encoded-queries openai-ada2-dl19-passage \
>   --output run.msmarco-v1-passage.openai-ada2.dl19.txt
Attempting to initialize pre-encoded queries openai-ada2-dl19-passage.
/home/jimmylin/.cache/pyserini/queries/query-embedding-openai-ada2-dl19-passage-20230530-e3a58f.ab57dab62c5b43508c661b78d6f7b6b9 already exists, skipping download.
Initializing openai-ada2-dl19-passage...
Attempting to initialize pre-built index msmarco-v1-passage.openai-ada2.
/home/jimmylin/.cache/pyserini/indexes/faiss.msmarco-v1-passage.openai-ada2.20230530.e3a58f.14725ced21bdcd0c9866aab1cfe8f2e0 already exists, skipping download.
Initializing msmarco-v1-passage.openai-ada2...
Running dl19-passage topics, saving to run.msmarco-v1-passage.openai-ada2.dl19.txt...
 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 42/43 [00:00<00:00, 51509.00it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tuna1/scratch/jimmylin/pyserini/pyserini/search/faiss/__main__.py", line 280, in <module>
    results = searcher.batch_search(batch_topics, batch_topic_ids, args.hits, threads=args.threads,
  File "/tuna1/scratch/jimmylin/pyserini/pyserini/search/faiss/_searcher.py", line 514, in batch_search
    D, I = self.index.search(q_embs, k)
  File "/tuna1/scratch/jimmylin/virtualenv/pyserini-dev2/lib/python3.8/site-packages/faiss/__init__.py", line 322, in replacement_search
    self.search_c(n, swig_ptr(x), k, swig_ptr(D), swig_ptr(I))
  File "/tuna1/scratch/jimmylin/virtualenv/pyserini-dev2/lib/python3.8/site-packages/faiss/swigfaiss.py", line 1652, in search
    return _swigfaiss.IndexFlat_search(self, n, x, k, distances, labels)
TypeError: in method 'IndexFlat_search', argument 3 of type 'float const *'
```

I was previously at:

```
$ pip list | grep faiss
faiss-cpu          1.7.2
```

Upgrading to 1.7.4 fixed the issue.

**Comment by lintool** [comment]
This regression passes with `faiss-cpu` 1.7.4:

```
python -m pyserini.2cr.msmarco --collection v1-passage --all --display-commands
```

All appears well. Closing issue.
