### ISSUE TITLE
ODQA NQ regression error

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1690]
On this regression:

```
nohup python -m pyserini.2cr.odqa --all --topic nq  --display-commands >& log.odqa.nq &
```

I'm getting errors:

```
Initializing wikipedia-dpr-100w.dpr-single-nq...
Running nq-test topics, saving to run.odqa.DPR.nq-test.hits-100.txt...
100%|██████████| 3610/3610 [29:58<00:00,  2.01it/s]
100%|██████████| 361000/361000 [01:50<00:00, 3280.58it/s]
Attempting to initialize pre-built index wikipedia-dpr-100w.dkrr-nq.
/u4/jimmylin/.cache/pyserini/indexes/faiss.wikipedia-dpr-100w.dkrr-dpr-nq-retriever.20220217.25ed1f.cc91b2.36a658e08dafb3e3313b05f88e001557 already exists, skipping download.
Initializing wikipedia-dpr-100w.dkrr-nq...
Running nq-test topics, saving to run.odqa.DPR-DKRR.nq-test.hits-1000.txt...
 14%|█▍        | 511/3610 [00:01<00:10, 290.85it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/u4/jimmylin/virtualenv/pyserini-pypi-test/lib/python3.10/site-packages/pyserini/search/faiss/__main__.py", line 280, in <module>
    results = searcher.batch_search(batch_topics, batch_topic_ids, args.hits, threads=args.threads,
  File "/u4/jimmylin/virtualenv/pyserini-pypi-test/lib/python3.10/site-packages/pyserini/search/faiss/_searcher.py", line 521, in batch_search
    q_embs = np.array([self.query_encoder.encode(q) for q in queries])
  File "/u4/jimmylin/virtualenv/pyserini-pypi-test/lib/python3.10/site-packages/pyserini/search/faiss/_searcher.py", line 521, in <listcomp>
    q_embs = np.array([self.query_encoder.encode(q) for q in queries])
  File "/u4/jimmylin/virtualenv/pyserini-pypi-test/lib/python3.10/site-packages/pyserini/search/faiss/_searcher.py", line 247, in encode
    embeddings = self._mean_pooling(outputs, inputs['attention_mask']).detach().cpu().numpy()
  File "/u4/jimmylin/virtualenv/pyserini-pypi-test/lib/python3.10/site-packages/pyserini/search/faiss/_searcher.py", line 235, in _mean_pooling
    model_output = model_output[0].masked_fill(1 - attention_mask[:, :, None], 0.)
RuntimeError: masked_fill_ only supports boolean masks, but got mask with dtype long int
0it [00:00, ?it/s]
Some weights of the model checkpoint at facebook/dpr-question_encoder-single-nq-base were not used when initializing DPRQuestionEncoder: ['question_encoder.bert_model.pooler.dense.weight', 'question_encoder.bert_model.pooler.dense.bias']
- This IS expected if you are initializing DPRQuestionEncoder from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DPRQuestionEncoder from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
```

I think it has something to do with dependency versions. In this env, I get *no* errors:

```bash
% pip list | egrep '(numpy|pyjnius|transformers|torch|sentencepiece|faiss-cpu|scikit-learn|lightgbm|spacy|pandas)\s'
faiss-cpu                1.7.4
lightgbm                 4.0.0
numpy                    1.25.2
pandas                   2.1.0
pyjnius                  1.5.0
scikit-learn             1.3.0
sentencepiece            0.1.99
spacy                    3.6.1
torch                    2.0.1
transformers             4.33.1
```

But in this env, I do get errors:

```bash
% pip list | egrep '(numpy|pyjnius|transformers|torch|sentencepiece|faiss-cpu|scikit-learn|lightgbm|spacy|pandas)\s'
faiss-cpu                1.7.4
lightgbm                 4.1.0
numpy                    1.26.1
pandas                   2.1.1
pyjnius                  1.6.0
scikit-learn             1.3.1
sentencepiece            0.1.99
spacy                    3.7.2
torch                    2.1.0
transformers             4.34.1
```

Both `linux.cs` virtualenvs.

**Comment by lintool** [comment]
Fixed by #1691
