### ISSUE TITLE
How to run custom topic on convert_trec_run_to_dpr_run

### ISSUE THREAD

**Issue by kerkathy** [castorini/pyserini#1793]
Hello

Basically I wanted to run HotpotQA's questions as query and run the Pyserini retrieval.
I've already convert the query and id to the assigned format `<id>\t<topic>` like mentioned in issue #1439 
The only difference is that because I'm using hotpotQA so the id doesn't start with 0
The `topics.tsv` file now looks like this
```
5a8b57f25542995d1e6f1371	Were Scott Derrickson and Ed Wood of the same nationality?
5a8c7595554299585d9e36b6	What government position was held by the woman who portrayed Corliss Archer in the film Kiss and Tell?
5a85ea095542994775f606a8	What science fantasy young adult series, told in first person, has a set of companion books narrating the stories of enslaved worlds and alien species?
```

And I can successfully run `pyserini.faiss.search` by assigning this file to `--topics`
Let's suppose the above generates `intermediate_file`

The problem occurs when I tried to run the conversion:
```
python -m pyserini.eval.convert_trec_run_to_dpr_retrieval_run \
  --topics-file topics.tsv \
  --topics-reader io.anserini.search.topicreader.TsvStringTopicReader \
  --index $luc_index_dir \
  --input $intermediate_file \
  --output $output_file \
  --store-raw \
```

An error says:
```
Traceback (most recent call last):                                                                                                           
  File "/home/guest/r11944026/anaconda3/envs/dpr/lib/python3.10/runpy.py", line 196, in _run_module_as_main                                  
    return _run_code(code, main_globals, None,                                                                                               
  File "/home/guest/r11944026/anaconda3/envs/dpr/lib/python3.10/runpy.py", line 86, in _run_code                                             
    exec(code, run_globals)                                                                                                                  
  File "/home/guest/r11944026/anaconda3/envs/dpr/lib/python3.10/site-packages/pyserini/eval/convert_trec_run_to_dpr_retrieval_run.py", line 5
8, in <module>                                                                                                                               
    question_id = int(question_id)                                                                                                           
ValueError: invalid literal for int() with base 10: '5a7166395542994082a3e814'   
```

Trace back, it seems that the error was raised here at `convert_trec_run_to_dpr_retrieval_run.py`
```
    if args.topics_file:
        qas = get_topics_with_reader(args.topics_reader, args.topics_file)

    ....

    with open(args.input) as f_in:
        for line in tqdm(f_in.readlines()):
            question_id, _, doc_id, _, score, _ = line.strip().split()
            question_id = int(question_id)
            question = qas[question_id]['title']
            answers = qas[question_id]['answers']
```

My question is, should I change the id in `topics.tsv` to 0-based so that the id is the same as row-number?
I'm confused because the ids in [example file](https://github.com/castorini/anserini-tools/blob/master/topics-and-qrels/topics.miracl-v1.0-en-dev.tsv) also didn't match the row number. However looking at `convert_trec_run_to_dpr_retrieval_run.py` it seems that we should do so...

Plus, does that change in id alone can fix the whole problem? Since there's `question = qas[question_id]['title']` and `answers = qas[question_id]['answers']` I wonder if we should also put 'title' and 'answers' columns in `topics.tsv`? If so, where?

Thanks in advance

**Comment by kerkathy** [comment]
Just for anyone's reference.

Turns out using `io.anserini.search.topicreader.DprNqTopicReader` together with a tsv file containing `<quesion>\t<answer>` in each line works :)

Also the key for context in each hit is called `passage` for `msmarco-v2-passage` index.
