### ISSUE TITLE
The anserini library does not load on Windows when the user name is in Chinese.

### ISSUE THREAD

**Issue by xzzvsxd** [castorini/pyserini#1880]
ERROR IS :
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\李星宇\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyserini\index\__init__.py", line 21, in <module>
    from .lucene._base import Document, Generator, IndexTerm, Posting, IndexReader
  File "C:\Users\李星宇\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyserini\index\lucene\__init__.py", line 17, in <module>
    from ._base import Document, Generator, IndexTerm, Posting, IndexReader
  File "C:\Users\李星宇\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyserini\index\lucene\_base.py", line 30, in <module>
    from pyserini.analysis import get_lucene_analyzer, JAnalyzer, JAnalyzerUtils
  File "C:\Users\李星宇\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyserini\analysis\__init__.py", line 17, in <module>
    from ._base import get_lucene_analyzer, Analyzer, JAnalyzer, JAnalyzerUtils, JDefaultEnglishAnalyzer, JWhiteSpaceAnalyzer
  File "C:\Users\李星宇\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyserini\analysis\_base.py", line 23, in <module>
    JAnalyzer = autoclass('org.apache.lucene.analysis.Analyzer')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\李星宇\AppData\Local\Programs\Python\Python312\Lib\site-packages\jnius\reflect.py", line 209, in autoclass
    c = find_javaclass(clsname)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "jnius\\jnius_export_func.pxi", line 22, in jnius.find_javaclass
  File "jnius\\jnius_utils.pxi", line 79, in jnius.check_exception
jnius.JavaException: JVM exception occurred: org/apache/lucene/analysis/Analyzer java.lang.NoClassDefFoundError

CURE IS :
Changing the path to the jar package that stores anserini to plain English will eliminate the error, but it will affect the experience.

**Comment by lintool** [comment]
Hi @xzzvsxd - thanks for reporting this. Noted.
