### ISSUE TITLE
Custom Query Generator

### ISSUE THREAD

**Issue by MarcosFP97** [castorini/pyserini#205]
Hi! I would like to know if there is the possibility of setting "querygenerator" option as in Anserini's search. I think this might be useful for users in order to modify their queries as they wish.

**Comment by lintool** [comment]
See this guide: https://github.com/castorini/pyserini/blob/master/docs/usage-querybuilder.md

**Comment by MarcosFP97** [comment]
Thanks! That was just what I was trying to find..
I am also having a problem when I try to import pyserini:

`from pyserini.search import pysearch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyserini/search/__init__.py", line 17, in <module>
    from ._base import Document, JDocument, JQuery, get_topics
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyserini/search/_base.py", line 24, in <module>
    from ..pyclass import autoclass
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyserini/pyclass.py", line 27, in <module>
    from jnius import autoclass, cast
  File "/home/user/anaconda3/lib/python3.7/site-packages/jnius/__init__.py", line 42, in <module>
    from .reflect import *  # noqa
  File "/home/user/anaconda3/lib/python3.7/site-packages/jnius/reflect.py", line 20, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/home/user/anaconda3/lib/python3.7/site-packages/six.py", line 827, in __new__
    return meta(name, bases, d)
  File "jnius/jnius_export_class.pxi", line 119, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 179, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 134, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 101, in jnius.create_jnienv
SystemError: Error calling dlopen(b'/usr/lib/jvm/java-11-openjdk-amd64/bin/lib/server/libjvm.so': b'/usr/lib/jvm/java-11-openjdk-amd64/bin/lib/server/libjvm.so: cannot open shared object file: No such file or directory'`

I've searched on Google and it seems that the problem is related to pyjnius package since it can't find the needed Java library. They have an open issue on this but it is not solved yet, I don't know if you have ever faced this problem...

I have also tried my code in Colab and there, it works

**Comment by lintool** [comment]
What Java version do you have installed on your system? For example, mine is:

```
$ java --version
java 11.0.4 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)
```

**Comment by MarcosFP97** [comment]
My version is:

`openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)`

And:
`$ echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-amd64/bin
`

**Comment by lintool** [comment]
I think this is related to https://github.com/castorini/pyserini/#known-issues

Try those instructions to see if they help.

**Comment by MarcosFP97** [comment]
Yes, that solved my issue, but now when I try to import pyserini I get the following message:
`>>> from pyserini.search import pysearch`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'pysearch' from 'pyserini.search' (/home/user/anaconda3/lib/python3.7/site-packages/pyserini/search/__init__.py)`

I don't know what's wrong now, since I am using pyserini 0.9.3.1 and pyjnius 1.3.0

**Comment by lintool** [comment]
The package layout changed from 0.9.3.0 to 0.9.3.1, see latest documentation: https://github.com/castorini/pyserini/#how-do-i-search

From `pyserini.search import SimpleSearcher` should work.

Sorry for the confusion, we had to do a package structure reorg as part of future proofing - see #163

**Comment by MarcosFP97** [comment]
That worked!
Not at all, congrats for the awesome work :)
