### ISSUE TITLE
Query embeddings not readable from Python 3.6

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#318]
Error is pretty straightforward:

```
$ python -m pyserini.dsearch --topics msmarco_passage_dev_subset \
>                              --index msmarco-passage-tct_colbert-hnsw \
>                              --encoded-queries msmarco-passage-dev-subset-tct_colbert \
>                              --output runs/run.msmarco-passage.tct_colbert.hnsw.tsv \
>                              --msmarco 
Attempting to initialize pre-encoded queries msmarco-passage-dev-subset-tct_colbert.
Downloading index at https://www.dropbox.com/s/l5ycxuzumi7fkl6/query-embedding-msmarco-passage-dev-subset-20210112-be7119.tar.gz?dl=1...
query-embedding-msmarco-passage-dev-subset-20210112-be7119.tar.gz: 19.1MB [00:03, 5.44MB/s]                                                                                                                                                                                              
Extracting /Users/jimmylin/.cache/pyserini/queries/query-embedding-msmarco-passage-dev-subset-20210112-be7119.tar.gz into /Users/jimmylin/.cache/pyserini/queries/query-embedding-msmarco-passage-dev-subset-20210112-be7119.c9398a713ff13e1780ea2aa2747deb2f...
Initializing msmarco-passage-dev-subset-tct_colbert...
Traceback (most recent call last):
  File "/anaconda3/envs/python36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/python36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jimmylin/workspace/pyserini/pyserini/dsearch/__main__.py", line 58, in <module>
    query_encoder = QueryEncoder.load_encoded_queries(args.encoded_queries)
  File "/Users/jimmylin/workspace/pyserini/pyserini/dsearch/_dsearcher.py", line 87, in load_encoded_queries
    return cls(encoded_query_dir=query_dir)
  File "/Users/jimmylin/workspace/pyserini/pyserini/dsearch/_dsearcher.py", line 46, in __init__
    self.embedding = self._load_embeddings(encoded_query_dir)
  File "/Users/jimmylin/workspace/pyserini/pyserini/dsearch/_dsearcher.py", line 91, in _load_embeddings
    df = pd.read_pickle(os.path.join(encoded_query_dir, 'embedding.pkl'))
  File "/anaconda3/envs/python36/lib/python3.6/site-packages/pandas/io/pickle.py", line 182, in read_pickle
    return pickle.load(f)
ValueError: unsupported pickle protocol: 5
```

See: https://stackoverflow.com/questions/63329657/python-3-7-error-unsupported-pickle-protocol-5

Since entire project assumes Python 3.6, can we re-pickle for backward compatibility? Are there any downsides to doing so?

**Comment by MXueguang** [comment]
should be easy to solve. will update for py36

**Comment by lintool** [comment]
ref: #322
