### ISSUE TITLE
Dense retrieval, on-the-fly query encoding: can't find model...

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#326]
```
$ python -m pyserini.dsearch --topics msmarco_passage_dev_subset \
>                              --index msmarco-passage-tct_colbert-hnsw \
>                              --encoder tct_colbert-msmarco \
>                              --output runs/run.msmarco-passage.tct_colbert.hnsw.tsv \
>                              --msmarco
404 Client Error: Not Found for url: https://huggingface.co/tct_colbert-msmarco/resolve/main/config.json
Traceback (most recent call last):
  File "/anaconda3/envs/python36/lib/python3.6/site-packages/transformers/configuration_utils.py", line 420, in get_config_dict
    use_auth_token=use_auth_token,
  File "/anaconda3/envs/python36/lib/python3.6/site-packages/transformers/file_utils.py", line 1044, in cached_path
    local_files_only=local_files_only,
  File "/anaconda3/envs/python36/lib/python3.6/site-packages/transformers/file_utils.py", line 1174, in get_from_cache
    r.raise_for_status()
  File "/Users/jimmylin/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/tct_colbert-msmarco/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/python36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/python36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jimmylin/workspace/pyserini/pyserini/dsearch/__main__.py", line 60, in <module>
    query_encoder = QueryEncoder(encoder_dir=args.encoder, device=args.device)
  File "/Users/jimmylin/workspace/pyserini/pyserini/dsearch/_dsearcher.py", line 41, in __init__
    self.model = BertModel.from_pretrained(encoder_dir)
  File "/anaconda3/envs/python36/lib/python3.6/site-packages/transformers/modeling_utils.py", line 962, in from_pretrained
    **kwargs,
  File "/anaconda3/envs/python36/lib/python3.6/site-packages/transformers/configuration_utils.py", line 372, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/anaconda3/envs/python36/lib/python3.6/site-packages/transformers/configuration_utils.py", line 432, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'tct_colbert-msmarco'. Make sure that:

- 'tct_colbert-msmarco' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'tct_colbert-msmarco' is the correct path to a directory containing a config.json file
```

**Comment by MXueguang** [comment]
ah, my bad, should be castorini/tct_colbert-msmarco.
I'll update the doc rn.

**Comment by MXueguang** [comment]
close by https://github.com/castorini/pyserini/pull/327
