### ISSUE TITLE
java.nio.file.NoSuchFileException using the Collection API

### ISSUE THREAD

**Issue by zeynepakkalyoncu** [castorini/pyserini#4]
All CACM HTML files are under `collection`. Instantiating `pycollection.Collection` with Python 3.5.0 and Java 11 leads to `java.nio.file.NoSuchFileException`:

```
from pyserini.collection import pycollection

collection = pycollection.Collection('HtmlCollection', 'collection/')
```

```
2019-11-22 08:05:07,954 ERROR [main] collection.DocumentCollection$2 (DocumentCollection.java:226) - Visiting failed for ä
java.nio.file.NoSuchFileException: ä
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149) ~[?:?]
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763) ~[?:?]
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219) ~[?:?]
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276) ~[?:?]
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322) ~[?:?]
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716) [?:?]
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796) [?:?]
	at io.anserini.collection.DocumentCollection.discover(DocumentCollection.java:232) [anserini-0.6.0-fatjar.jar:?]
	at io.anserini.collection.DocumentCollection.iterator(DocumentCollection.java:110) [anserini-0.6.0-fatjar.jar:?]
```

**Comment by lintool** [comment]
Hrm. I'm unable to replicate the error. My Python:

```
$ python --version
Python 3.6.7 :: Anaconda, Inc.
```

@ronakice @rodrigonogueira4 can either of you try this and let us know?
https://github.com/castorini/pyserini#usage-of-the-collection-api

Should be cut and paste...

**Comment by lintool** [comment]
Follow-up @zeynepakkalyoncu 
Seems to work in colab: https://colab.research.google.com/drive/1HDt39zkg-7L6fy9Wv9H8C4MbNQoOpfeC

**Comment by zeynepakkalyoncu** [comment]
The latest Pyjnius [update](https://pypi.org/project/pyjnius/) fixed it for me too. Closing.
