### ISSUE TITLE
Broken test: test_tokenize_json.py

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#469]
@stephaniewhoo can you please fix?

```
.Epython3: can't open file '../pyserini/tokenize_json_collection.py': [Errno 2] No such file or directory
E.....
======================================================================
ERROR: test_bert_dir (tests.test_tokenize_json.TestTokenizeJson)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/tests/test_tokenize_json.py", line 46, in test_bert_dir
    os.mkdir(indir)
FileExistsError: [Errno 17] File exists: './test_tokenize_json'

======================================================================
ERROR: test_bert_single_file (tests.test_tokenize_json.TestTokenizeJson)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/tests/test_tokenize_json.py", line 32, in test_bert_single_file
    with open(outj,'r') as ret:
FileNotFoundError: [Errno 2] No such file or directory: 'out_test_bert_single_file.json'

----------------------------------------------------------------------
```

**Comment by stephaniewhoo** [comment]
fixed by [PR](https://github.com/castorini/pyserini/pull/470)
