### ISSUE TITLE
Cannot install in development mode

### ISSUE THREAD

**Issue by hnt4499** [castorini/pyserini#529]
Hi,

I am new to Pyserini. I followed steps in https://github.com/castorini/pyserini#development-installation to try to install this package  in development mode (to try out DPR retrieval model), but I got `java.lang.NoClassDefFoundError` error when running unit test:

```
======================================================================
ERROR: tests.test_querybuilder (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_querybuilder
Traceback (most recent call last):
  File "/home/jupyter/miniconda3/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/jupyter/miniconda3/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/mnt/c/Users/jupyter/openqa/pyserini/tests/test_querybuilder.py", line 25, in <module>
    from pyserini.analysis import get_lucene_analyzer
  File "/mnt/c/Users/jupyter/openqa/pyserini/pyserini/analysis/__init__.py", line 17, in <module>
    from ._base import get_lucene_analyzer, Analyzer, JAnalyzer, JAnalyzerUtils, JDefaultEnglishAnalyzer, JWhiteSpaceAnalyzer
  File "/mnt/c/Users/jupyter/openqa/pyserini/pyserini/analysis/_base.py", line 37, in <module>
    JFreebaseAnalyzer = autoclass('io.anserini.analysis.FreebaseAnalyzer')
  File "/home/jupyter/miniconda3/lib/python3.8/site-packages/jnius/reflect.py", line 229, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: io/anserini/analysis/FreebaseAnalyzer java.lang.NoClassDefFoundError
```
May I how I can solve this? Thank you

**Comment by MXueguang** [comment]
Hi @hnt4499 
Could you double check if the fatjar file built from Anserini was copied to `pyserini/resources/jars/` properly?

**Comment by hnt4499** [comment]
I am not sure whether it is `pyserini/pyserini/resources/jars` or `pyserini/resources/jars`. I have copied the fat jar file to the former one:
```
$ ls pyserini/pyserini/resources/jars/
anserini-0.12.1-SNAPSHOT-fatjar.jar
```

**Comment by MXueguang** [comment]
Hi @hnt4499,
I just figure out it is due to our recent update on Anserini https://github.com/castorini/anserini/commit/c83ae4756dfbd923abce07134001999cd2939cdd , we removed that class but didn't remove the corresponding code in Pyserini. We will do the update.

Meanwhile, I think you can ignore that unittest for now. The DPR retrieval model should regardless of this issue.

**Comment by MXueguang** [comment]
fixing in https://github.com/castorini/pyserini/pull/530

**Comment by hnt4499** [comment]
Hi @MXueguang,

Thank you for your reply. Actually I wanted to run BM25 retrieval part, but I got the same error:
```
$ python -m pyserini.search --topics dpr-nq-test \
                            --index wikipedia-dpr \
                            --output runs/run.dpr.nq-test.bm25.trec

Traceback (most recent call last):
  File "/home/jupyter/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jupyter/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/jupyter/openqa/pyserini/pyserini/search/__main__.py", line 23, in <module>
    from pyserini.analysis import JDefaultEnglishAnalyzer, JWhiteSpaceAnalyzer
  File "/mnt/c/Users/jupyter/openqa/pyserini/pyserini/analysis/__init__.py", line 17, in <module>
    from ._base import get_lucene_analyzer, Analyzer, JAnalyzer, JAnalyzerUtils, JDefaultEnglishAnalyzer, JWhiteSpaceAnalyzer
  File "/mnt/c/Users/jupyter/openqa/pyserini/pyserini/analysis/_base.py", line 37, in <module>
    JFreebaseAnalyzer = autoclass('io.anserini.analysis.FreebaseAnalyzer')
  File "/home/jupyter/miniconda3/lib/python3.8/site-packages/jnius/reflect.py", line 208, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 28, in jnius.find_javaclass
jnius.JavaException: Class not found b'io/anserini/analysis/FreebaseAnalyzer'
```

**Comment by MXueguang** [comment]
I see. I'll fix it soon.

**Comment by hnt4499** [comment]
Thank you!

**Comment by MXueguang** [comment]
@hnt4499 since merging to master branch need waiting for CR from @lintool.
Could you manually remove these lines followed by https://github.com/castorini/pyserini/pull/530/files
This will fix the issue.

**Comment by hnt4499** [comment]
Thank you, it works!
