### ISSUE TITLE
Broken RRF tests

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#533]
hey @yuki617 - I think you broke some of the tests?

```
======================================================================
FAIL: test_reciprocal_rank_fusion_simple (tests.test_fusion.TestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jimmylin/workspace/pyserini/tests/test_fusion.py", line 33, in test_reciprocal_rank_fusion_simple
    self.assertTrue(filecmp.cmp(verify_path, self.output_path))
AssertionError: False is not true

======================================================================
FAIL: test_discard_qrels (tests.test_trectools.TestTrecTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jimmylin/workspace/pyserini/tests/test_trectools.py", line 46, in test_discard_qrels
    self.assertTrue(filecmp.cmp('tests/resources/simple_trec_run_remove_verify.txt', self.output_path))
AssertionError: False is not true

======================================================================
FAIL: test_normalize_scores (tests.test_trectools.TestTrecTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jimmylin/workspace/pyserini/tests/test_trectools.py", line 58, in test_normalize_scores
    self.assertTrue(filecmp.cmp('tests/resources/simple_trec_run_normalize_verify.txt', self.output_path))
AssertionError: False is not true

======================================================================
FAIL: test_retain_qrels (tests.test_trectools.TestTrecTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jimmylin/workspace/pyserini/tests/test_trectools.py", line 53, in test_retain_qrels
    self.assertTrue(filecmp.cmp('tests/resources/simple_trec_run_keep_verify.txt', self.output_path))
AssertionError: False is not true

======================================================================
FAIL: test_trec_run_read (tests.test_trectools.TestTrecTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jimmylin/workspace/pyserini/tests/test_trectools.py", line 33, in test_trec_run_read
    self.assertTrue(filecmp.cmp(verify_path, self.output_path))
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by lintool** [comment]
Closed by #537
