### ISSUE TITLE
Class not found b'io/anserini/analysis/DefaultEnglishAnalyzer'

### ISSUE THREAD

**Issue by PepijnBoers** [castorini/pyserini#61]
Obtained a JavaException error after importing:
`from pyserini.search import pysearch`

--> Error:
`... jnius.JavaException: Class not found b'io/anserini/analysis/DefaultEnglishAnalyzer'`

Installed Pyserini via:
`pip install pyserini --user`

I was not able to resolve this, I tried:
- replacing the fatjar with a newly built Anserini 0.8.1 fatjar
- manual configuration of classpath via configure_classpath() method in pyserini.setup.

------------------
Complete error:

`Traceback (most recent call last):
  File "build_db.py", line 6, in <module>
    from pyserini.search import pysearch
  File "/home/pboers/.local/lib/python3.7/site-packages/pyserini/search/pysearch.py", line 25, in <module>
    from ..pyclass import JSearcher, JResult, JDocument, JString, JArrayList, JTopics, JTopicReader
  File "/home/pboers/.local/lib/python3.7/site-packages/pyserini/pyclass.py", line 51, in <module>
    JDefaultEnglishAnalyzer = autoclass('io.anserini.analysis.DefaultEnglishAnalyzer')
  File "/home/pboers/.local/lib/python3.7/site-packages/jnius/reflect.py", line 208, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 28, in jnius.find_javaclass
jnius.JavaException: Class not found b'io/anserini/analysis/DefaultEnglishAnalyzer'`

**Comment by PepijnBoers** [comment]
Issue only occurs on one specific machine.

**Comment by PepijnBoers** [comment]
Issue was caused by running an older Java version (8), upgrading to Java 11 solved this problem.
