### ISSUE TITLE
Encoded queries: unsupported pickle protocol

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#675]
Should probably check in the test cases?

```
======================================================================
ERROR: test_msmarco_passage_tct_colbert_v2_hn_encoded_queries (integrations.dense.test_tct_colbert-v2.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jimmylin/workspace/pyserini/integrations/dense/test_tct_colbert-v2.py", line 129, in test_msmarco_passage_tct_colbert_v2_hn_encoded_queries
    encoder = QueryEncoder.load_encoded_queries('tct_colbert-v2-hn-msmarco-passage-dev-subset')
  File "/Users/jimmylin/workspace/pyserini/pyserini/dsearch/_dsearcher.py", line 77, in load_encoded_queries
    return cls(encoded_query_dir=query_dir)
  File "/Users/jimmylin/workspace/pyserini/pyserini/dsearch/_dsearcher.py", line 49, in __init__
    self.embedding = self._load_embeddings(encoded_query_dir)
  File "/Users/jimmylin/workspace/pyserini/pyserini/dsearch/_dsearcher.py", line 81, in _load_embeddings
    df = pd.read_pickle(os.path.join(encoded_query_dir, 'embedding.pkl'))
  File "/anaconda3/envs/python36/lib/python3.6/site-packages/pandas/io/pickle.py", line 182, in read_pickle
    return pickle.load(f)
ValueError: unsupported pickle protocol: 5
```

**Comment by MXueguang** [comment]
```======================================================================
FAIL: test_msmarco_passage_tct_colbert_v2_bf_otf (integrations.dense.test_tct_colbert-v2.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/x93ma/pyserini/integrations/dense/test_tct_colbert-v2.py", line 54, in test_msmarco_passage_tct_colbert_v2_bf_otf
    self.assertAlmostEqual(score, 0.3439, places=4)
AssertionError: 0.344 != 0.3439 within 4 places

======================================================================
FAIL: test_msmarco_passage_tct_colbert_v2_hnp_bf_bm25_hybrid_otf (integrations.dense.test_tct_colbert-v2.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/x93ma/pyserini/integrations/dense/test_tct_colbert-v2.py", line 106, in test_msmarco_passage_tct_colbert_v2_hnp_bf_bm25_hybrid_otf
    self.assertAlmostEqual(score, 0.3683, places=4)
AssertionError: 0.3619 != 0.3683 within 4 places

======================================================================
FAIL: test_msmarco_passage_tct_colbert_v2_hnp_bf_d2q_hybrid_otf (integrations.dense.test_tct_colbert-v2.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/x93ma/pyserini/integrations/dense/test_tct_colbert-v2.py", line 124, in test_msmarco_passage_tct_colbert_v2_hnp_bf_d2q_hybrid_otf
    self.assertAlmostEqual(score, 0.3730, places=4)
AssertionError: 0.3721 != 0.373 within 4 places

----------------------------------------------------------------------
Ran 8 tests in 11940.090s

FAILED (failures=3)
```
got 3 error after fix the protocol
