### ISSUE TITLE
Integration failures at v0.13.0

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#689]
I'm getting integration failures on `orca`:

```
======================================================================
FAIL: test_dpr_curated_test_bf_bm25_hybrid_otf (test_dpr.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/store/scratch/jimmylin/pyserini/integrations/dense/test_dpr.py", line 239, in test_dpr_curated_test_bf_bm25_hybrid_otf
    self.assertAlmostEqual(score, 0.9006, places=4)
AssertionError: 0.3314 != 0.9006 within 4 places

======================================================================
FAIL: test_dpr_curated_test_bf_otf (test_dpr.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/store/scratch/jimmylin/pyserini/integrations/dense/test_dpr.py", line 215, in test_dpr_curated_test_bf_otf
    self.assertAlmostEqual(score, 0.8876, places=4)
AssertionError: 0.3285 != 0.8876 within 4 places

----------------------------------------------------------------------
```

**Comment by MXueguang** [comment]
@lintool  this should be closed by https://github.com/castorini/pyserini/pull/692

**Comment by lintool** [comment]
Agreed.
