### ISSUE TITLE
subprocess.CalledProcessError: Command '['which', 'javac']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by XY2323819551** [castorini/pyserini#729]
Hi, sorry to bother you! I really want to know how to solve the issue.

I want to do deeper searching with your code, my target is that I can debug you code in Pycharm. Firstly, I tried to debug the code which have reproduced the DPR results.   I made it with command【python -m pyserini.dsearch --topics dpr-nq-test \
                           --index /home/zhangxy/QA/castorini/pyserini/indexes/dindex-wikipedia-dpr_multi-bf-20200127-f403c3 \
                           --encoded-queries /home/zhangxy/QA//castorini/pyserini/query_encoders/query-embedding-dpr_multi-nq-test-20210419-9323ec \
                           --output runs/run.dpr.nq-test.multi.bf.trec \
                           --batch-size 36 \
                           --threads 12】

so I guess I could debug your code if I add the following commands in the /pyserini/dsearch/__main__.py's Edit Configuration->parameters
【--topics dpr-nq-test --index /home/zhangxy/QA/castorini/pyserini/indexes/dindex-wikipedia-dpr_multi-bf-20200127-f403c3 --encoded-queries /home/zhangxy/QA/castorini/pyserini/query_encoders/query-embedding-dpr_multi-nq-test-20210419-9323ec --output /home/zhangxy/QA/castorini/pyserini/runs/run.dpr.nq-test.multi.bf.trec --batch-size 36  --device cuda】

but I got the following errors:
ssh://zhangxy@10.10.10.54:22/home/zhangxy/anaconda3/envs/pyserini/bin/python3.7 -u /home/zhangxy/QA/castorini/pyserini/pyserini/dsearch/__main__.py --topics dpr-nq-test --index /home/zhangxy/QA/castorini/pyserini/indexes/dindex-wikipedia-dpr_multi-bf-20200127-f403c3 --encoded-queries /home/zhangxy/QA/castorini/pyserini/query_encoders/query-embedding-dpr_multi-nq-test-20210419-9323ec --output /home/zhangxy/QA/castorini/pyserini/runs/run.dpr.nq-test.multi.bf.trec --batch-size 36 --device cuda
2021-08-08 12:38:23.949245: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/home/zhangxy/QA/castorini/pyserini/pyserini/dsearch/__main__.py", line 22, in <module>
    from pyserini.dsearch import SimpleDenseSearcher, BinaryDenseSearcher, TctColBertQueryEncoder, \
  File "/home/zhangxy/QA/castorini/pyserini/pyserini/dsearch/__init__.py", line 17, in <module>
    from ._dsearcher import DenseSearchResult, SimpleDenseSearcher, BinaryDenseSearcher, QueryEncoder, \
  File "/home/zhangxy/QA/castorini/pyserini/pyserini/dsearch/_dsearcher.py", line 35, in <module>
    from pyserini.search import SimpleSearcher, Document
  File "/home/zhangxy/QA/castorini/pyserini/pyserini/search/__init__.py", line 17, in <module>
    from ._base import Document, JDocument, JQuery, JDisjunctionMaxQueryGenerator, get_topics, get_topics_with_reader, get_qrels_file, get_qrels
  File "/home/zhangxy/QA/castorini/pyserini/pyserini/search/_base.py", line 26, in <module>
    from ..pyclass import autoclass
  File "/home/zhangxy/QA/castorini/pyserini/pyserini/pyclass.py", line 27, in <module>
    from jnius import autoclass, cast
  File "/home/zhangxy/anaconda3/envs/pyserini/lib/python3.7/site-packages/pyjnius-1.3.0-py3.7-linux-x86_64.egg/jnius/__init__.py", line 42, in <module>
    from .reflect import *  # noqa
  File "/home/zhangxy/anaconda3/envs/pyserini/lib/python3.7/site-packages/pyjnius-1.3.0-py3.7-linux-x86_64.egg/jnius/reflect.py", line 20, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/home/zhangxy/anaconda3/envs/pyserini/lib/python3.7/site-packages/six.py", line 872, in __new__
    return meta(name, resolved_bases, d)
  File "jnius/jnius_export_class.pxi", line 119, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 179, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 134, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 84, in jnius.create_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 47, in jnius.find_java_home
  File "/home/zhangxy/anaconda3/envs/pyserini/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/zhangxy/anaconda3/envs/pyserini/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'javac']' returned non-zero exit status 1.

Process finished with exit code 1

So, how can I debug your code successfully? Is there another way to achieve it ? Thank you very much!!

**Comment by lintool** [comment]
I haven't come across this error before... I assume you've followed the instructions on how to set up a dev installation?
https://github.com/castorini/pyserini/#development-installation

In particular, did you build the Anserini fatjar and put it in the right location?

**Comment by lintool** [comment]
Closing. I assume #731 is the follow-up.
