### ISSUE TITLE
ImportErrors and Transformer version

### ISSUE THREAD

**Issue by apokali** [castorini/pyserini#734]
Hello

I was trying reproduce https://github.com/castorini/pyserini/blob/master/docs/experiments-msmarco-passage.md Pyserini: BM25 Baseline for MS MARCO Passage Retrieval. For the step where we  index these docs as a JsonCollection using Anserini:

```bash
python -m pyserini.index -collection JsonCollection -generator DefaultLuceneDocumentGenerator \
 -threads 9 -input collections/msmarco-passage/collection_jsonl \
 -index indexes/lucene-index-msmarco-passage -storePositions -storeDocvectors -storeRaw
```
The following errors occur
```bash
Traceback (most recent call last):
  File "/u3/x232lin/anaconda3/envs/pyserini/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/u3/x232lin/anaconda3/envs/pyserini/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/u3/x232lin/anaconda3/envs/pyserini/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/u3/x232lin/URA/pyserini/pyserini/index/__init__.py", line 17, in <module>
    from ._base import Generator, IndexTerm, Posting, IndexReader
  File "/u3/x232lin/URA/pyserini/pyserini/index/_base.py", line 29, in <module>
    from ..search import Document
  File "/u3/x232lin/URA/pyserini/pyserini/search/__init__.py", line 20, in <module>
    from ._impact_searcher import JImpactSearcherResult, ImpactSearcher
  File "/u3/x232lin/URA/pyserini/pyserini/search/_impact_searcher.py", line 26, in <module>
    from pyserini.index import IndexReader
ImportError: cannot import name 'IndexReader'
```

Another issue is with the pip installation. Regarding the post #567 , I tried to install transformers==4.5.0, but when I ran the unit test in the environment, the following errors occur
```bash
======================================================================
ERROR: pyserini.hsearch (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyserini.hsearch
Traceback (most recent call last):
  File "/u3/x232lin/anaconda3/envs/pyserini/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/u3/x232lin/anaconda3/envs/pyserini/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/u3/x232lin/URA/pyserini/pyserini/hsearch/__init__.py", line 17, in <module>
    from ._hybrid import HybridSearcher
  File "/u3/x232lin/URA/pyserini/pyserini/hsearch/_hybrid.py", line 23, in <module>
    from pyserini.dsearch import SimpleDenseSearcher, DenseSearchResult
  File "/u3/x232lin/URA/pyserini/pyserini/dsearch/__init__.py", line 17, in <module>
    from ._dsearcher import DenseSearchResult, SimpleDenseSearcher, BinaryDenseSearcher, QueryEncoder, \
  File "/u3/x232lin/URA/pyserini/pyserini/dsearch/_dsearcher.py", line 31, in <module>
    from transformers.file_utils import is_faiss_available, requires_backends
ImportError: cannot import name 'requires_backends'
```

If I installed transformers==4.6.0, the issues no longer existed.

Thanks, Xuntian

**Comment by MXueguang** [comment]
Hi @apokali ,
> ImportError: cannot import name 'IndexReader'

this error was just fixed, please pull latest code.

>ImportError: cannot import name 'requires_backends'
yes, please use transformers>=4.6.0, the post #567 is a bit outdated

**Comment by lintool** [comment]
@MXueguang can this be closed?

**Comment by MXueguang** [comment]
yes
