### ISSUE TITLE
ValueError in uniCOIL (w/ doc2query-T5) for MS MARCO (V1)

### ISSUE THREAD

**Issue by apokali** [castorini/pyserini#777]
Hi

I was trying to reproduce the experiment https://github.com/castorini/pyserini/blob/master/docs/experiments-unicoil.md.

In the step where we run the retrieval for MS MARCO
```bash
wget https://rgw.cs.uwaterloo.ca/JIMMYLIN-bucket0/data/topics.msmarco-passage.dev-subset.unicoil.tsv.gz -P collections/

python -m pyserini.search --topics collections/topics.msmarco-passage.dev-subset.unicoil.tsv.gz \
                          --index indexes/lucene-index.msmarco-passage-unicoil-b8 \
                          --output runs/run.msmarco-passage-unicoil-b8.tsv \
                          --impact \
                          --hits 1000 --batch 36 --threads 12 \
                          --output-format msmarco
```

The following error occurred
```bash
Traceback (most recent call last):
  File "/u3/x232lin/anaconda3/envs/pyserini/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/u3/x232lin/anaconda3/envs/pyserini/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/u3/x232lin/URA/pyserini/pyserini/search/__main__.py", line 127, in <module>
    query_iterator = get_query_iterator(args.topics, TopicsFormat(args.topics_format))
  File "/u3/x232lin/URA/pyserini/pyserini/query_iterator.py", line 151, in get_query_iterator
    return mapping[topics_format].from_topics(topics_path)
  File "/u3/x232lin/URA/pyserini/pyserini/query_iterator.py", line 85, in from_topics
    topics = get_topics_with_reader('io.anserini.search.topicreader.TsvIntTopicReader', topics_path)
  File "/u3/x232lin/URA/pyserini/pyserini/search/_base.py", line 243, in get_topics_with_reader
    raise ValueError(f'Unable to initialize TopicReader {reader_class} with file {file}!')
ValueError: Unable to initialize TopicReader io.anserini.search.topicreader.TsvIntTopicReader with file collections/topics.msmarco-passage.dev-subset.unicoil.tsv.gz!
```

Thanks, Xuntian

**Comment by MXueguang** [comment]
Hi @apokali, I think with `.gz` file, we need to use the latest Anserini build.
I.e. Do https://github.com/castorini/pyserini#development-installation with `fat.jar` file from latest Anserini code.
Otherwise, you have to unzip the `.gz` topic and use `tsv` directly.

**Comment by apokali** [comment]
@MXueguang Thank you, problem solved!
