### ISSUE TITLE
Test failures on DPR and TCT

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#778]
hey @MXueguang @jacklin64 @justram I'm getting the following test failures.

Please take a look and let's figure out what happened?

```
======================================================================
FAIL: test_msmarco_passage_distilbert_kd_bf_otf (test_distilbert_kd.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_distilbert_kd.py", line 54, in test_msmarco_passage_distilbert_kd_bf_otf
    self.assertEqual(stderr, '')
AssertionError: "2021-09-22 07:18:04.913620: W tensorflow[346 chars]e.\n" != ''
- 2021-09-22 07:18:04.913620: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
- 2021-09-22 07:18:04.913652: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


======================================================================
FAIL: test_msmarco_passage_distilbert_kd_tas_b_bf_otf (test_distilbert_tasb.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_distilbert_tasb.py", line 54, in test_msmarco_passage_distilbert_kd_tas_b_bf_otf
    self.assertEqual(stderr, '')
AssertionError: "2021-09-22 07:51:27.791594: W tensorflow[346 chars]e.\n" != ''
- 2021-09-22 07:51:27.791594: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
- 2021-09-22 07:51:27.791625: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


======================================================================
FAIL: test_dpr_curated_test_bf_bm25_hybrid_otf (test_dpr.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_dpr.py", line 241, in test_dpr_curated_test_bf_bm25_hybrid_otf
    self.assertAlmostEqual(score, 0.9006, places=4)
AssertionError: 0.8948 != 0.9006 within 4 places

======================================================================
FAIL: test_dpr_nq_test_bf_bm25_hybrid_otf (test_dpr.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_dpr.py", line 83, in test_dpr_nq_test_bf_bm25_hybrid_otf
    self.assertAlmostEqual(score, 0.8260, places=4)
AssertionError: 0.7989 != 0.826 within 4 places

======================================================================
FAIL: test_dpr_squad_test_bf_bm25_hybrid_otf (test_dpr.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_dpr.py", line 293, in test_dpr_squad_test_bf_bm25_hybrid_otf
    self.assertAlmostEqual(score, 0.7511, places=4)
AssertionError: 0.7227 != 0.7511 within 4 places

======================================================================
FAIL: test_dpr_trivia_test_bf_bm25_hybrid_otf (test_dpr.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_dpr.py", line 135, in test_dpr_trivia_test_bf_bm25_hybrid_otf
    self.assertAlmostEqual(score, 0.8264, places=4)
AssertionError: 0.8154 != 0.8264 within 4 places

======================================================================
FAIL: test_dpr_wq_test_bf_bm25_hybrid_otf (test_dpr.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_dpr.py", line 187, in test_dpr_wq_test_bf_bm25_hybrid_otf
    self.assertAlmostEqual(score, 0.7712, places=4)
AssertionError: 0.7534 != 0.7712 within 4 places

======================================================================
FAIL: test_msmarco_passage_sbert_bf_otf (test_sbert.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_sbert.py", line 54, in test_msmarco_passage_sbert_bf_otf
    self.assertEqual(stderr, '')
AssertionError: "2021-09-23 00:04:54.081441: W tensorflow[346 chars]e.\n" != ''
- 2021-09-23 00:04:54.081441: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
- 2021-09-23 00:04:54.081472: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


======================================================================
FAIL: test_msmarco_doc_tct_colbert_bf_bm25_hybrid_otf (test_tct_colbert.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_tct_colbert.py", line 151, in test_msmarco_doc_tct_colbert_bf_bm25_hybrid_otf
    self.assertAlmostEqual(score, 0.3701, places=4)
AssertionError: 0.3366 != 0.3701 within 4 places

======================================================================
FAIL: test_msmarco_doc_tct_colbert_bf_d2q_hybrid_otf (test_tct_colbert.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_tct_colbert.py", line 170, in test_msmarco_doc_tct_colbert_bf_d2q_hybrid_otf
    self.assertAlmostEqual(score, 0.3784, places=4)
AssertionError: 0.3489 != 0.3784 within 4 places

======================================================================
FAIL: test_msmarco_passage_tct_colbert_bf_bm25_hybrid_otf (test_tct_colbert.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_tct_colbert.py", line 88, in test_msmarco_passage_tct_colbert_bf_bm25_hybrid_otf
    self.assertAlmostEqual(score, 0.3529, places=4)
AssertionError: 0.3415 != 0.3529 within 4 places

======================================================================
FAIL: test_msmarco_passage_tct_colbert_bf_d2q_hybrid_otf (test_tct_colbert.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_tct_colbert.py", line 106, in test_msmarco_passage_tct_colbert_bf_d2q_hybrid_otf
    self.assertAlmostEqual(score, 0.3647, places=4)
AssertionError: 0.3548 != 0.3647 within 4 places

----------------------------------------------------------------------
```

**Comment by jacklin64** [comment]
<img width="1216" alt="截圖 2021-09-23 下午6 12 46" src="https://user-images.githubusercontent.com/18071510/134590990-4ed36ba2-6387-4052-b20f-811c62bc8c32.png">
It seems that one of the errors comes from the warning from importing tensorflow ? When I run msmarco evaluation using pyserini I got the same warning message.

**Comment by justram** [comment]
Checking TCT, there's only a small diff till f614111

======================================================================
FAIL: test_msmarco_doc_tct_colbert_bf_bm25_hybrid_otf (test_tct_colbert.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/store/scratch/j587yang/project/pyserini/integrations/dense/test_tct_colbert.py", line 151, in test_msmarco_doc_tct_colbert_bf_bm25_hybrid_otf
    self.assertAlmostEqual(score, 0.3701, places=4)
AssertionError: 0.3692 != 0.3701 within 4 places (0.0009000000000000119 difference)

======================================================================
FAIL: test_msmarco_doc_tct_colbert_bf_d2q_hybrid_otf (test_tct_colbert.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/store/scratch/j587yang/project/pyserini/integrations/dense/test_tct_colbert.py", line 170, in test_msmarco_doc_tct_colbert_bf_d2q_hybrid_otf
    self.assertAlmostEqual(score, 0.3784, places=4)
AssertionError: 0.3769 != 0.3784 within 4 places (0.0015000000000000013 difference)

======================================================================
FAIL: test_msmarco_doc_tct_colbert_bf_otf (test_tct_colbert.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/store/scratch/j587yang/project/pyserini/integrations/dense/test_tct_colbert.py", line 132, in test_msmarco_doc_tct_colbert_bf_otf
    self.assertAlmostEqual(score, 0.3323, places=4)
AssertionError: 0.3236 != 0.3323 within 4 places (0.008699999999999986 difference)

**Comment by lintool** [comment]
I'm running again based on fix at #780 - will report back results.

**Comment by lintool** [comment]
I'm getting this now:

```
======================================================================
FAIL: test_msmarco_passage_distilbert_kd_bf_otf (test_distilbert_kd.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_distilbert_kd.py", line 54, in test_msmarco_passage_distilbert_kd_bf_otf
    self.assertEqual(stderr, '')
AssertionError: "2021-09-24 22:17:52.443778: W tensorflow[346 chars]e.\n" != ''
- 2021-09-24 22:17:52.443778: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
- 2021-09-24 22:17:52.443810: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


======================================================================
FAIL: test_msmarco_passage_distilbert_kd_tas_b_bf_otf (test_distilbert_tasb.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_distilbert_tasb.py", line 54, in test_msmarco_passage_distilbert_kd_tas_b_bf_otf
    self.assertEqual(stderr, '')
AssertionError: "2021-09-24 22:47:38.350740: W tensorflow[346 chars]e.\n" != ''
- 2021-09-24 22:47:38.350740: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
- 2021-09-24 22:47:38.350773: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


======================================================================
FAIL: test_msmarco_passage_sbert_bf_otf (test_sbert.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/dense/test_sbert.py", line 54, in test_msmarco_passage_sbert_bf_otf
    self.assertEqual(stderr, '')
AssertionError: "2021-09-25 18:35:58.518755: W tensorflow[346 chars]e.\n" != ''
- 2021-09-25 18:35:58.518755: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
- 2021-09-25 18:35:58.518786: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


----------------------------------------------------------------------
```

Seems to be related to #781 ...

**Comment by lintool** [comment]
Trying again, post #784.

**Comment by lintool** [comment]
At commit `fa237ac355b6c902d916ecc9ed01a930e9f29b7c`, on `damiano`.

```
----------------------------------------------------------------------
Ran 43 tests in 116077.886s

OK
```

🎉
