### ISSUE TITLE
clprf failing tests

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#787]
```
======================================================================
FAIL: test_core18 (test_clprf.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/clprf/test_clprf.py", line 321, in test_core18
    self.assertTrue(self.core18_checker.run('core18_bm25', '--bm25', 0.2495))
AssertionError: False is not true

======================================================================
FAIL: test_core18_lr (test_clprf.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/clprf/test_clprf.py", line 346, in test_core18_lr
    self.assertAlmostEqual(score, 0.2837, delta=0.0001)
AssertionError: 0.2839 != 0.2837 within 0.0001 delta

======================================================================
FAIL: test_core18_rm3 (test_clprf.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/clprf/test_clprf.py", line 324, in test_core18_rm3
    self.assertTrue(self.core18_checker.run('core18_bm25', '--bm25 --rm3', 0.3135))
AssertionError: False is not true

======================================================================
FAIL: test_core18_svm (test_clprf.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/clprf/test_clprf.py", line 390, in test_core18_svm
    self.assertAlmostEqual(score, 0.2840, delta=0.0001)
AssertionError: 0.2841 != 0.284 within 0.0001 delta

======================================================================
FAIL: test_core18_svm_rm3 (test_clprf.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/clprf/test_clprf.py", line 412, in test_core18_svm_rm3
    self.assertAlmostEqual(score, 0.3219, delta=0.0001)
AssertionError: 0.3216 != 0.3219 within 0.0001 delta

----------------------------------------------------------------------
```

My environment:

```
$ pip list | egrep '(pyjnius|transformers|torch|sentencepiece|faiss-cpu|scikit-learn|lightgbm|spacy)\s'
faiss-cpu               1.7.0
lightgbm                3.2.1
pyjnius                 1.3.0
scikit-learn            0.24.2
sentencepiece           0.1.95
spacy                   3.0.6
torch                   1.8.1
transformers            4.6.1
```

On Linux.

Differences are small, but we should still check out...

**Comment by lintool** [comment]
Tests pass on my iMac Pro:

```
$ pip list | egrep '(pyjnius|transformers|torch|sentencepiece|faiss-cpu|scikit-learn|lightgbm|spacy)\s'
faiss-cpu                     1.7.0
lightgbm                      3.2.1
pyjnius                       1.3.0
scikit-learn                  0.24.2
sentencepiece                 0.1.95
spacy                         3.0.6
torch                         1.8.1
transformers                  4.6.1
```

Strange...

**Comment by lintool** [comment]
Digging into this more, we have this basic failure, once again, on `damiano`:

```
$ python -m unittest integrations.clprf.test_clprf.TestSearchIntegration.test_core18
-------------------------
Running core18_bm25:
-------------------------
Running core18 topics, saving to verify.pyserini.core18_bm25.txt...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:06<00:00,  7.87it/s]
map                   	all	0.2496
P_30                  	all	0.3573
map                   	all	0.2496
P_30                  	all	0.3573

F
======================================================================
FAIL: test_core18 (integrations.clprf.test_clprf.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/clprf/test_clprf.py", line 321, in test_core18
    self.assertTrue(self.core18_checker.run('core18_bm25', '--bm25', 0.2495))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 9.629s
```

**Comment by lintool** [comment]
Ah, got it!

Issue is here: https://github.com/castorini/anserini/blob/master/docs/regressions-log.md#september-2-2021

Regressions using old indexes still pass, but fail for up-to-date index. So yes, regression numbers need to be recalibrated.

**Comment by lintool** [comment]
Fix confirmed on Linux and Mac.
