### ISSUE TITLE
KeyError when reproducing deepimpact on MSMARCO

### ISSUE THREAD

**Issue by Qiaoyf96** [castorini/pyserini#792]
Hi,

I am trying to reproduce the deepimpact result on MSMARCO following https://github.com/castorini/pyserini/blob/master/docs/experiments-deepimpact.md, but received the following error:

```
$ python -m pyserini.search --topics ../msmarco-deepimpact-pyserini/collections/topics.msmarco-passage.dev-subset.deep-impact.tsv --index ../msmarco-deepimpact-pyserini/indexes/lucene-index.msmarco-passage-deepimpact-b8 --output ../msmarco-deepimpact-pyserini/runs/run.msmarco-passage-deepimpact-b8.tsv --impact --hits 1000 --batch 36 --threads 12 --output-format msmarco
Running ../msmarco-deepimpact-pyserini/collections/topics.msmarco-passage.dev-subset.deep-impact.tsv topics, saving to ../msmarco-deepimpact-pyserini/runs/run.msmarco-passage-deepimpact-b8.tsv...
  1%|▉                                                                                                                                                                                    | 35/6980 [00:00<00:01, 3849.20it/s]
Traceback (most recent call last):
  File "/home/yifan/anaconda3/envs/pyserini/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yifan/anaconda3/envs/pyserini/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yifan/Downloads/pyserini/pyserini/search/__main__.py", line 242, in <module>
    batch_topics, batch_topic_ids, args.hits, args.threads, fields=fields
  File "/home/yifan/Downloads/pyserini/pyserini/search/_impact_searcher.py", line 156, in batch_search
    if self.idf[token] > self.min_idf:
KeyError: 'cyclopeanbinocularmonoculartrichromatic'
```

Could you please take another look? Thank you in advance for your help.

**Comment by MXueguang** [comment]
@Qiaoyf96  It seems like a bug caused by a recent change will fix it soon.

**Comment by Qiaoyf96** [comment]
Got it. Thanks!

**Comment by MXueguang** [comment]
should be fix in this PR https://github.com/castorini/pyserini/pull/793

**Comment by lintool** [comment]
@Qiaoyf96 Once you are able to reproduce, please contribute to our log: https://github.com/castorini/pyserini/blob/master/docs/experiments-deepimpact.md#reproduction-log

**Comment by Qiaoyf96** [comment]
Thanks! I have successfully reproduced the result and created a PR to update the log.
