### ISSUE TITLE
Broken LTR test case

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#879]
Starting from an empty index cache, I'm getting the following:

```
Traceback (most recent call last):
  File "scripts/ltr_msmarco/ltr_inference.py", line 233, in <module>
    searcher = MsmarcoLtrSearcher(args.model, args.ibm_model, args.index, args.data)
  File "./pyserini/ltr/search_msmarco/_search_msmarco.py", line 39, in __init__
    self.fe = FeatureExtractor(index, max(multiprocessing.cpu_count()//2, 1))
  File "./pyserini/ltr/_base.py", line 211, in __init__
    self.utils = JFeatureExtractorUtils(index_dir, worker_num)
  File "jnius/jnius_export_class.pxi", line 271, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 385, in jnius.JavaClass.call_constructor
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: no segments* file found in MMapDirectory@/Users/jimmylin/.cache/pyserini/indexes/index-msmarco-document-ltr-20211027-3e4c283.2718874ab44f6d383e84ad20f3790460 lockFactory=org.apache.lucene.store.NativeFSLockFactory@1583741e: files: [] org.apache.lucene.index.IndexNotFoundException
Traceback (most recent call last):
  File "scripts/ltr_msmarco/generate_document_score_withmaxP.py", line 14, in <module>
    with open(args.input) as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'ltr_test/run.ltr.msmarco-passage.test.trec'
Traceback (most recent call last):
  File "tools/scripts/msmarco/msmarco_doc_eval.py", line 235, in <module>
    main(parser.parse_args())
  File "tools/scripts/msmarco/msmarco_doc_eval.py", line 222, in main
    metrics = compute_metrics_from_files(path_to_reference, path_to_candidate, exclude_qids)
  File "tools/scripts/msmarco/msmarco_doc_eval.py", line 184, in compute_metrics_from_files
    qids_to_ranked_candidate_documents = load_candidate(path_to_candidate)
  File "tools/scripts/msmarco/msmarco_doc_eval.py", line 98, in load_candidate
    with autoopen(path_to_candidate,'r') as f:
  File "tools/scripts/msmarco/msmarco_doc_eval.py", line 28, in autoopen
    return open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'ltr_test/run.ltr.msmarco-passage.test.tsv'
```

Seems like the test case assumes the index is already there? We should make the test case more robust...

**Comment by lintool** [comment]
The error manifests as:

```
======================================================================
ERROR: test_reranking (test_ltr_msmarco_document.TestLtrMsmarcoPassage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jimmylin/workspace/pyserini/integrations/sparse/test_ltr_msmarco_document.py", line 56, in test_reranking
    result = subprocess.check_output(f'python tools/scripts/msmarco/msmarco_doc_eval.py --judgments tools/topics-and-qrels/qrels.msmarco-doc.dev.txt --run ltr_test/{outp_tsv}', shell=True).decode(sys.stdout.encoding)
  File "/anaconda3/envs/python36/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/anaconda3/envs/python36/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python tools/scripts/msmarco/msmarco_doc_eval.py --judgments tools/topics-and-qrels/qrels.msmarco-doc.dev.txt --run ltr_test/run.ltr.msmarco-passage.test.tsv' returned non-zero exit status 1.

----------------------------------------------------------------------
```
