### ISSUE TITLE
Dense index with T5 model failed

### ISSUE THREAD

**Issue by hl2659** [castorini/pyserini#912]
I tried to use  castorini/monot5-base-med-msmarco for dense indexing. 
python -m pyserini.encode input --corpus integrations/resources/sample_collection_jsonl --fields title text output --embeddings indexes/dindex-sample-monot5-base-msmarco --to-faiss encoder --encoder castorini/monot5-base-msmarco --fields title text --batch 8

It fails with the following trackback:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/pyserini/pyserini/encode/__main__.py", line 101, in <module>
    embeddings = encoder.encode(**kwargs)
  File "/content/pyserini/pyserini/encode/_auto.py", line 46, in encode
    outputs = self.model(**inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/t5/modeling_t5.py", line 1414, in forward
    return_dict=return_dict,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/t5/modeling_t5.py", line 902, in forward
    raise ValueError(f"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds")
ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds

I googled this issue, and people mentioned that for t5 model, the forward method requires either decoder_input_ids or decoder_inputs_embeds. 

Is there any different way to index with t5 model? 

Thanks!

**Comment by ronakice** [comment]
`castorini/monot5-base-msmarco` and `castorini/monot5-base-med-msmarco` are cross-encoders so they are not trained for dense encoding. I suggest you take a look at [PyGaggle](https://github.com/castorini/pygaggle) for instructions on how to use them or use another one of the dense encoders we provide in Pyserini.
