### ISSUE TITLE
Errors with SPLADEv2 MS MARCO instructions

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#994]
Here: https://github.com/castorini/pyserini/blob/master/docs/experiments-spladev2.md

If I download the Naver model and try to run it, I get the following error:

```
Traceback (most recent call last):
  File "/scratch2/jimmylin/virtualenv/pyserini-dev/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1364, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location="cpu")
  File "/scratch2/jimmylin/virtualenv/pyserini-dev/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/scratch2/jimmylin/virtualenv/pyserini-dev/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

@MXueguang can you take a look?

**Comment by lintool** [comment]
Closed by #996
